# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 45437243ba1ef5fc2c4395969d609b77d862e18d2586d3fd9a74505f7301c4deefb4df4370372d399680123bb414cb11c328a91e10bffd4064c8383b009b7976

test:
  secret_key_base: 63927604a54720d5380cfa6f3b6af765eb3b7edfae120b0fec43942096366e467318cf83686c36ac17a8f83eabf444a657443d6603971537a1e1fa115d0aefaa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
